name: CI
#Github, gitlab, bitbucket
#Jenkins, Github actions, CirlceCi

#Cuando queremos que suceda este worfklow
on:
  pull_request:
    branches:
      - main
  #Esto es para cuando YA se integra, no esta mal que lo haga, es opciona, el mandatorio es el de arriba.
  push:
    branches:
      - main

#Los actions son como plugins que alguien hizo y se puede utilizar
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Descargando el repo
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Instalar el gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Buildiear el proyecto
        run: ./gradlew build
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Crear y subir la imagen
        with:
          image: danielsabana/guarderia
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USUARIO }}
          password: ${{ secrets.DOCKER_CLAVE }}